#' Add a continuous reproducibility check to a Nix-pinned project
#'
#' Writes a GitHub Actions workflow that rebuilds the project's pinned Nix
#' environment from its `default.nix`, runs the project's analysis and/or
#' rendering commands inside it, and (optionally) verifies that the outputs
#' committed to the repository are still reproduced.
#'
#' The project must already contain a `default.nix`, for example one
#' generated by `rix::rix()`. This function deliberately does not create
#' one: rix defines the environment, rixcheck proves it still works.
#'
#' @param run Character vector of shell commands executed inside
#'   `nix-shell`, in order, e.g.
#'   `c("Rscript Simulation/06_run_all.R", "quarto render Manuscript/article.qmd")`.
#' @param outputs Optional character vector of paths (files or directories,
#'   as understood by `git ls-files`) holding committed outputs to compare
#'   against the freshly produced ones, e.g. `"Simulation/results"`. When
#'   `NULL` (default), the check only verifies that `run` succeeds.
#'   Point this at data outputs (`.rds`, `.csv`), not at rendered PDF/HTML:
#'   rendered documents embed dates and are never bitwise stable.
#' @param tolerance Optional numeric tolerance for comparing `.rds` outputs
#'   via `all.equal()`. When `NULL` (default), all comparisons are bitwise
#'   (file hashes), which is the appropriate expectation for a pinned
#'   environment on a fixed platform. Set a tolerance only for outputs of
#'   genuinely nondeterministic steps (multithreaded BLAS, parallel RNG).
#' @param schedule Cron expression for periodically re-running the check, or
#'   `NULL` to only run on push. Defaults to monthly, so the project learns
#'   that its recipe has decayed before a reader does.
#' @param workflow File name of the workflow to write.
#'
#' @return Invisibly, the path to the written workflow file.
#' @export
use_repro_check <- function(run,
                            outputs = NULL,
                            tolerance = NULL,
                            schedule = "0 8 1 * *",
                            workflow = "repro-check.yml") {
  stopifnot(is.character(run), length(run) >= 1)
  if (!file.exists("default.nix")) {
    stop("No default.nix found in the current directory.\n",
         "Generate one first, e.g. with rix::rix(date = ..., r_pkgs = ...).",
         call. = FALSE)
  }

  # type = "sh": the commands run in the Linux CI shell, so quoting must not
  # depend on the platform where the workflow is generated
  run_steps <- paste0(
    "      - run: nix-shell default.nix --run ",
    shQuote(run, type = "sh"), collapse = "\n")

  schedule_block <- if (is.null(schedule)) "" else
    paste0("  schedule:\n    - cron: '", schedule, "'")

  compare_step <- ""
  if (!is.null(outputs)) {
    write_compare_script()
    tol_arg <- if (is.null(tolerance)) "" else
      paste0(" --tolerance ", format(tolerance, scientific = TRUE))
    compare_step <- paste0(
      "      - run: nix-shell default.nix --run ",
      shQuote(paste0("Rscript tools/repro-compare.R ",
                     paste(outputs, collapse = " "), tol_arg),
              type = "sh"))
  }

  template <- readLines(
    system.file("templates", "repro-check.yml", package = "rixcheck"),
    warn = FALSE)
  yml <- paste(template, collapse = "\n")
  yml <- sub("{{SCHEDULE}}", schedule_block, yml, fixed = TRUE)
  yml <- sub("{{RUN_STEPS}}", run_steps, yml, fixed = TRUE)
  yml <- sub("{{COMPARE_STEP}}", compare_step, yml, fixed = TRUE)
  yml <- gsub("\n{3,}", "\n\n", yml)

  dir.create(".github/workflows", recursive = TRUE, showWarnings = FALSE)
  path <- file.path(".github", "workflows", workflow)
  writeLines(yml, path)

  message("Wrote ", path)
  if (!is.null(outputs)) message("Wrote tools/repro-compare.R")
  message("Commit these files and push; the check runs on GitHub Actions.")
  invisible(path)
}

write_compare_script <- function() {
  dir.create("tools", showWarnings = FALSE)
  file.copy(
    system.file("templates", "repro-compare.R", package = "rixcheck"),
    file.path("tools", "repro-compare.R"),
    overwrite = TRUE)
}
